// node tests/render/gen_prewarm.mjs: plays the REAL game from the title to the end card (the e2e bot, Low tier) and
// writes every material x mesh-shape pair the render system handed out to src/render/prewarm.ts. Run it again whenever
// an asset gains or loses a material, a vertex-colour layer, a UV1 or a skin (tests/render/prewarm.test.mjs says so).
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, startServer } from '../harness.mjs';
import { openBot } from '../e2e/lib/bot.mjs';

const server = await startServer({});
let list = [];
try {
  const bot = await openBot(server, { piece: 'code-render', tier: 'low', viewport: { width: 640, height: 360 }, allowErrors: true });
  try {
    await bot.startFromTitle();
    const run = await bot.play({ until: 'ending' });
    list = await bot.page.evaluate(() => window.__dbg.ext.render.recipes());
    console.log(`played to '${run.state}' at tick ${run.tick}: ${list.length} recipes`);
    if (run.state !== 'ending' && !process.argv.includes('--force')) throw new Error(`the run stopped in '${run.state}' at ${run.checkpoint}: nothing written`);
  } finally { await bot.game.browser.close().catch(() => {}); }
} finally { await server.close(); }
const body = `// GENERATED by tests/render/gen_prewarm.mjs from a whole playthrough of the real game: do not edit by hand.
// Every material x mesh-shape pair the stage hands out (MaterialFactory.note). RenderSystem.warmUp compiles them behind
// the first loading screen; tests/render/prewarm.test.mjs fails when a playthrough meets a pair that is not listed.
export const PREWARM: readonly string[] = [
${list.map((l) => '  ' + JSON.stringify(l) + ',').join('\n')}
];
`;
fs.writeFileSync(path.join(ROOT, 'src/render/prewarm.ts'), body);
console.log('wrote src/render/prewarm.ts');
