// Polish round 3 (performance critic): no shader program is LINKED while she plays. Every program of the stage is in
// src/render/prewarm.ts (generated by gen_prewarm.mjs) and is compiled behind the first loading screen; the sun of the
// High tier keeps casting, so no doorway changes the lights three compiles by. Measured the critic's way: linkProgram is
// hooked after "Begin" and every link is noted with the game's state.
//   Low    from the title through the hatch stage and the stair swap; then the proving lift's swap to the coda
//   High   the same first leg (the shadow pass's three depth programs, the doorway of the Tally House)
// If this fails after an asset changed (a new material, vertex-colour layer, UV1 or skin): node tests/render/gen_prewarm.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { startServer } from '../harness.mjs';
import { openBot } from '../e2e/lib/bot.mjs';

function hook() {
  const P = WebGL2RenderingContext.prototype, src = new WeakMap(), att = new WeakMap(), L = window.__late = [];
  const ss = P.shaderSource; P.shaderSource = function (s, t) { src.set(s, t); return ss.call(this, s, t); };
  const as = P.attachShader; P.attachShader = function (p, s) { const a = att.get(p) || []; a.push(s); att.set(p, a); return as.call(this, p, s); };
  const lp = P.linkProgram; P.linkProgram = function (p) {
    const t = (att.get(p) || []).map((s) => src.get(s) || ''), frag = t[1] || t[0] || '';
    const name = (frag.match(/#define SHADER_NAME (\S+)/) || [])[1] || '?';
    const defs = [...new Set(t.join('\n').match(/#define (USE_\w+|[A-Z_]{3,})\b/g) || [])].map((d) => d.replace('#define ', '')).filter((d) => !/^(SHADER_NAME|HIGH_PRECISION|PI_HALF|RECIPROCAL_PI|EPSILON|KEEP_K_DECL|KEEP_K|OPAQUE)$/.test(d));
    const ctx = window.__dbg.ext.core.ctx();
    L.push({ tick: ctx.clock.tick, state: ctx.state.current, cell: ctx.world.cell, name, defs: defs.join(' ') });
    return lp.call(this, p);
  };
}
const describe = (rows) => rows.map((r) => `tick ${r.tick} ${r.cell} ${r.name} [${r.defs}]`).join('; ');

for (const tier of ['low', 'high']) {
  test(`${tier}: no program links in play from the title to the gallery${tier === 'low' ? ', nor on the way to the far rim' : ''}`, async () => {
    const server = await startServer({});
    try {
      const bot = await openBot(server, { piece: 'r3-fix-code-render', tier, viewport: { width: 480, height: 270 }, allowErrors: true });
      try {
        await bot.page.evaluate(() => { for (let k = 0; k < 3; k++) window.__dbg.step(0, true); });
        await bot.startFromTitle();
        await bot.page.evaluate(hook);
        const programs0 = await bot.page.evaluate(() => window.__dbg.ext.render.programs());
        const run = await bot.play({ until: 'cp_gallery_bay', frameEvery: 4 });
        assert.equal(run.checkpoint, 'cp_gallery_bay', `the bot reached the gallery (state ${run.state})`);
        let rows = await bot.page.evaluate(() => window.__late.splice(0));
        let late = rows.filter((r) => r.state === 'playing');
        console.log(`${tier}: title -> cp_gallery_bay (tick ${run.tick}): ${rows.length} links, ${late.length} of them in play; ${programs0} programs at "Begin" (round 2 ${tier === 'low' ? 'Low: 4' : 'High: 17'} in play)`);
        assert.equal(late.length, 0, `programs linked in play: ${describe(late)}`);
        if (tier === 'low') {
          await bot.jump('cp_boss_proven');
          await bot.page.evaluate(() => window.__late.splice(0));              // a debug jump is a loading screen
          const coda = await bot.play({ until: 'cp_rim', frameEvery: 4 });
          assert.equal(coda.checkpoint, 'cp_rim', `the bot reached the rim (state ${coda.state})`);
          rows = await bot.page.evaluate(() => window.__late.splice(0));
          late = rows.filter((r) => r.state === 'playing');
          console.log(`low: cp_boss_proven -> cp_rim (tick ${coda.tick}): ${late.length} links in play (round 2: 3)`);
          assert.equal(late.length, 0, `programs linked in play: ${describe(late)}`);
        }
        // every pair the run handed out is one prewarm.ts lists
        const { missing, listed } = await bot.page.evaluate(async () => {
          const { PREWARM } = await import('/src/render/prewarm.ts');
          const have = new Set(PREWARM);
          return { missing: window.__dbg.ext.render.recipes().filter((r) => !have.has(r)), listed: PREWARM.length };
        });
        console.log(`${tier}: ${listed} recipes listed, ${missing.length} met that are not`);
        assert.deepEqual(missing, [], 'run node tests/render/gen_prewarm.mjs');
        const flags = await bot.page.evaluate(() => ({ check: window.__dbg.ext.render.system().renderer.debug.checkShaderErrors, dev: window.__dbg.ext.core.ctx().flags.dev }));
        assert.equal(flags.check, flags.dev, 'three reads the shader logs only for a developer');
      } finally { await bot.game.browser.close().catch(() => {}); }
    } finally { await server.close(); }
  });
}
