// node tools/build-assets.mjs [--only <id|owner|piece>[,...]] [--placeholders] [--reset <id>[,...]] [--force] [--jobs n] [--manifest overlay.json] [--verbose] [--allow-stale-lightmap]
//
// THE ONE COMMAND (ARCHITECTURE 7.1). `npm run assets` runs it.
//
//   textures -> props, weapons, enemies, boss -> zones -> late bakes -> optimise -> check
//
//   * an item with a source script is built from it:  tools/blender.sh ... -P <source> -- --out <raw path> --seed 1
//     (a `.mjs` source, e.g. tools/gen_fx_atlas.mjs for tx_fx / tx_noise, is run as `node <source> --out blender/export/tex`);
//   * an item WITHOUT a source script is a placeholder: left alone, or (re)generated by blender/placeholders.py when
//     --placeholders is given. A placeholder never replaces a final file;
//   * --reset <id>[,...] is the way BACK from a scripted asset to its placeholder: for an id whose source script does not
//     exist (you removed or renamed it) it deletes the final raw export, its .deps.json, the shipped file and the stamp,
//     then regenerates the placeholder (as `--placeholders --only <id>`). It refuses an id whose script still exists;
//   * a lightmap whose `source` is a zone script is that zone's by-product (bake.save_lightmap writes it). A script whose
//     meshes point at such a lightmap (extra `lightmap` / `lightLayer`) and which did NOT write it in the same run FAILS:
//     the new GLB carries a new UV1 atlas and would sample a stale or placeholder lightmap. --allow-stale-lightmap ships
//     it anyway (iterating on geometry with the bake switched off) and says so on the asset's line;
//   * zones are built after everything else and are rebuilt when the raw export of a prop they embedded changes;
//   * every raw export is optimised into public/assets and checked against the manifest (tools/check-glb.mjs).
//
// Outputs newer than their inputs are skipped. "Inputs" (compared by content hash, blender/export/.stamp/):
//   * the source script, every blender/lib/**/*.py, design/*.json (and blender/tex/*.py for shared textures);
//   * every project module the script imported last time (a helper beside it: `import common`), recorded by
//     export.export_asset in <raw>.deps.json. A helper that is not imported (read as data, exec'd) is NOT seen: use --force;
//   * the ENTRIES of the texture tables (blender/lib/palette.json, tx_*_trim.json, mask_regions.json) the script read
//     through lib.manifest: an appended palette cell or mask region rebuilds nothing, a changed one rebuilds its users;
//   * for zones, the raw exports of the props they embedded;
//   * a lightmap with a bake script of its own (lm_surface <- bake_surface.py, a "late" item run after the zones) is tracked
//     the same way: bake.save_lightmap writes <raw png>.deps.json (imported helper modules, embedded props). When an asset
//     that points at such a lightmap is rebuilt and the lightmap is stale but not part of the run, the run prints
//     `STALE <lightmap>` with the command that builds them together and exits 1 (--allow-stale-lightmap: exit 0).
// NOTHING IS SHIPPED UNTIL IT PASSES: Blender writes under temporary names, the optimiser writes a temporary file beside
// the target, check-glb judges that file, and only then are the raw export, its lightmaps and the shipped files renamed
// into place together. A FAILED item leaves the previous raw export and shipped file exactly as they were.
// --only takes asset ids, texture ids, manifest owners (props_mech, env_interior, render ...) or pieces (art-props).
// One line per item: built / skipped / kept / FAILED with the reason. The full Blender log of each item is in
// blender/export/.logs/<id>.log; lines of it that start with WARNING (bake warnings: buried vertices, double-lit faces,
// a chunk over its share) are counted on the item's line, "(2 warnings: see <log>)", and printed in full by --verbose.
// Exit code 1 on any failure.
// Safe to run by several people at once on different owners: every file is written under a temporary name and renamed,
// and an item being built by another run is waited for, not built twice.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { ROOT, rel, readJson, loadManifest, loadLayout, overlayArg, select, allIds, hashFiles, listFiles, writeFileAtomic,
  glbIsPlaceholder, pngIsPlaceholder, fmtBytes, tableEntriesHash, glbJson } from './pipeline-lib.mjs';
import { optimizeAsset, optimizeTexture } from './optimize-assets.mjs';
import { checkAsset, checkTexture } from './check-glb.mjs';

const TOOL_VERSION = 'build-assets 3';
const BLENDER = path.join(ROOT, 'tools/blender.sh');
const t0 = performance.now();
const secs = (t) => ((performance.now() - t) / 1000).toFixed(1) + ' s';

// ---------------------------------------------------------------- arguments
const argv = process.argv.slice(2);
const overlay = overlayArg(argv);
const flag = (n) => { const i = argv.indexOf(n); if (i < 0) return false; argv.splice(i, 1); return true; };
const value = (n) => { const out = []; let i; while ((i = argv.indexOf(n)) >= 0) { out.push(argv[i + 1]); argv.splice(i, 2); } return out; };
const RESET = value('--reset').flatMap((s) => String(s).split(',')).filter(Boolean);
const PLACEHOLDERS = flag('--placeholders') || RESET.length > 0, FORCE = flag('--force'), VERBOSE = flag('--verbose'), NO_CHECK = flag('--no-check'),
  ALLOW_STALE_LM = flag('--allow-stale-lightmap');
const only = [...value('--only').flatMap((s) => String(s).split(',')).filter(Boolean), ...RESET];
const JOBS = Math.max(1, Number(value('--jobs')[0] ?? Math.min(6, Math.max(1, os.cpus().length - 2))));
if (flag('--help') || flag('-h') || argv.length) {
  if (argv.length) console.error(`unknown argument(s): ${argv.join(' ')}`);
  console.log('node tools/build-assets.mjs [--only <id|owner|piece>[,...]] [--placeholders] [--reset <id>[,...]] [--force] [--jobs n] [--manifest overlay.json] [--verbose] [--allow-stale-lightmap]');
  process.exit(argv.length ? 2 : 0);
}

const M = loadManifest(overlay), L = loadLayout();
// --reset: back to the placeholder. Only for an id without a source script on disk; everything final about it is removed
// here, so the placeholder generator (which never replaces a final file) builds it afresh below.
for (const id of RESET) {
  const e = M.assets[id] ?? M.textures[id];
  if (!e) { console.error(`--reset: '${id}' is not an asset or texture id`); process.exit(2); }
  if (e.source && fs.existsSync(path.join(ROOT, e.source))) {
    console.error(`--reset ${id}: its source script ${e.source} exists, so the build makes it from that script. Remove or rename the script first (a reset deletes the final file and regenerates the placeholder).`);
    process.exit(2);
  }
  // the lightmaps that script wrote as by-products go with it (they have no other producer)
  const ids = [id, ...(M.assets[id] && e.source ? Object.entries(M.textures).filter(([, t]) => t.source === e.source).map(([t]) => t) : [])];
  for (const x of ids) {
    const d = M.assets[x] ?? M.textures[x];
    const stamp = path.join(path.dirname(path.dirname(d._raw)), '.stamp', x + '.json');
    const gone = [d._raw, d._raw + '.deps.json', d._pub, stamp].filter((f) => fs.existsSync(f));
    for (const f of gone) fs.rmSync(f, { force: true });
    console.log(`reset    ${x}: removed ${gone.map((f) => rel(f)).join(', ') || 'nothing (no file was there)'}`);
    if (x !== id) only.push(x);
  }
}
let sel;
try { sel = only.length ? select(M, only) : allIds(M, false); } catch (e) { console.error(e.message); process.exit(2); }

// ---------------------------------------------------------------- inputs shared by everything
const LIB = path.join(ROOT, 'blender/lib');
const texScripts = listFiles(path.join(ROOT, 'blender/tex'), (p) => p.endsWith('.py'));
const designFiles = ['design/assets.json', 'design/layout.json', 'design/story.json'].map((p) => path.join(ROOT, p));
const sha = (s) => crypto.createHash('sha1').update(s).digest('hex');
const fileSha = (f) => (fs.existsSync(f) ? sha(fs.readFileSync(f)) : 'missing');
const COMMON = sha([TOOL_VERSION, hashFiles(designFiles), overlay ? hashFiles([overlay]) : '', hashFiles(listFiles(LIB, (p) => p.endsWith('.py')))].join('|'));
const PLACEHOLDER_PY = path.join(ROOT, 'blender/placeholders.py');
// a shipped file is re-checked (not rebuilt) when the checker itself changed
const CHECKER = hashFiles(['tools/check-glb.mjs', 'tools/layout_geom.mjs', 'tools/pipeline-lib.mjs'].map((p) => path.join(ROOT, p)));
const TAG = `${process.pid}.tmp`;                                       // temporary names of this run
const tablesHash = (used) => tableEntriesHash(LIB, used);

// ---------------------------------------------------------------- items
const assetSources = new Set(Object.values(M.assets).map((a) => a.source));
function makeItem(kind, id) {
  const e = kind === 'asset' ? M.assets[id] : M.textures[id];
  const src = e.source ? path.join(ROOT, e.source) : null;
  const has = !!src && fs.existsSync(src);
  let producer, stage;
  if (kind === 'texture') {
    if (has && src.endsWith('.mjs')) { producer = 'node'; stage = 'tex'; }
    else if (has && assetSources.has(e.source)) { producer = 'byproduct'; stage = 'late'; }
    else if (has) { producer = 'script'; stage = e.source.startsWith('blender/tex/') ? 'tex' : 'late'; }
    else { producer = 'placeholder'; stage = 'tex'; }
  } else {
    producer = has ? 'script' : 'placeholder';
    stage = e.chunks ? 'zone' : 'asset';
  }
  const rawDir = path.dirname(path.dirname(e._raw));
  return { kind, id, e, src, producer, stage, raw: e._raw, pub: e._pub, stamp: path.join(rawDir, '.stamp', id + '.json'), log: path.join(rawDir, '.logs', id + '.log'),
    lock: path.join(rawDir, '.stamp', id + '.lock'), status: null, note: '', t: 0, staged: null, done: false, after: null, warnings: [], stale: [] };
}
const items = [...sel.textures.map((id) => makeItem('texture', id)), ...sel.assets.map((id) => makeItem('asset', id))];
const byId = new Map(items.map((it) => [it.id, it]));
const readStamp = (it) => { try { return readJson(it.stamp); } catch { return {}; } };
const writeStamp = (it, s) => writeFileAtomic(it.stamp, JSON.stringify(s));
const readDeps = (it) => { try { return readJson(it.raw + '.deps.json'); } catch { return null; } };
/** Lightmaps and layers a script-built asset writes as by-products (textures whose `source` is the asset's script). */
const byproductsOf = (it) => (it.kind === 'asset' && it.producer === 'script'
  ? Object.entries(M.textures).filter(([, t]) => t.source && t.source === it.e.source).map(([id]) => id) : []);
/** The item of a by-product texture: the selected one, or one made now so it is optimised, checked and reported too. */
function byproductItem(id, owner) {
  let b = byId.get(id);
  if (!b) { b = makeItem('texture', id); byId.set(id, b); items.push(b); }
  b.after = owner.id;
  return b;
}
const stagedPng = (texId) => path.join(path.dirname(M.textures[texId]._raw), `.${texId}.${TAG}.png`);     // bake.save_lightmap writes here (KS_STAGE_TAG)

function embeddedOf(it, deps) {
  // what a zone embedded last time (written by export.export_asset), else every `placedBy: zone` asset of its sets
  if (deps?.embedded) return deps.embedded;
  if (!it.e.chunks) return [];
  return Object.entries(M.assets).filter(([, a]) => a.placedBy === 'zone' && (a.sets ?? []).some((s) => (it.e.sets ?? []).includes(s))).map(([id]) => id);
}
function inputsHash(it) {
  const parts = [COMMON, it.producer];
  if (it.producer === 'placeholder') parts.push(fileSha(PLACEHOLDER_PY));
  else if (it.src) parts.push(fileSha(it.src));
  if (it.kind === 'texture' && it.stage === 'tex') parts.push(hashFiles(texScripts));
  // an asset, or a lightmap with a bake script of its own (lm_surface: bake.save_lightmap writes its deps.json)
  if (it.kind === 'asset' || (it.producer === 'script' && it.stage === 'late')) {
    const deps = readDeps(it);
    for (const dep of embeddedOf(it, deps)) parts.push(dep + ':' + fileSha(M.assets[dep]?._raw ?? ''));
    for (const m of deps?.modules ?? []) parts.push(m + ':' + fileSha(path.join(ROOT, m)));
    parts.push(tablesHash(deps?.tables ?? null));
  }
  return sha(parts.join('|'));
}
function stale(it) {
  if (FORCE) return true;
  if (!fs.existsSync(it.raw)) return true;
  const s = readStamp(it);
  return s.inputs !== inputsHash(it);
}
const rm = (...files) => { for (const f of files) if (f) fs.rmSync(f, { force: true, recursive: true }); };
function dropStaged(it) {
  if (!it.staged) return;
  rm(it.staged.raw, it.staged.raw + '.deps.json');
  it.staged = null;
}

// ---------------------------------------------------------------- running things
function run(cmd, args, logFile, env = {}) {
  return new Promise((resolve) => {
    fs.mkdirSync(path.dirname(logFile), { recursive: true });
    const p = spawn(cmd, args, { cwd: ROOT, env: { ...process.env, ...(overlay ? { KS_MANIFEST_OVERLAY: overlay } : {}), ...env } });
    let out = '';
    p.stdout.on('data', (d) => { out += d; if (VERBOSE) process.stdout.write(d); });
    p.stderr.on('data', (d) => { out += d; if (VERBOSE) process.stderr.write(d); });
    const timer = setTimeout(() => { out += '\nTIMEOUT: killed after 30 minutes\n'; p.kill('SIGKILL'); }, 30 * 60 * 1000);
    p.on('error', (e) => { clearTimeout(timer); out += `\n${e.message}\n`; fs.writeFileSync(logFile, out); resolve({ code: 1, out }); });
    p.on('close', (code) => { clearTimeout(timer); fs.writeFileSync(logFile, out); resolve({ code: code ?? 1, out }); });
  });
}
/** The reason a Blender run failed: the last Python exception with its message lines. */
function reason(out) {
  const lines = out.split('\n');
  let last = -1;
  for (let i = 0; i < lines.length; i++) if (/^[A-Za-z_.]*(Error|Exception|Exit|Interrupt)\b.*:/.test(lines[i]) && !lines[i].startsWith('Error: script failed') && !/^EGL Error|^MESA: error/.test(lines[i])) last = i;
  if (last < 0) {
    const t = lines.filter((l) => l.trim() && !/^EGL Error|^MESA: error|^Blender |^Info:|INFO/.test(l));
    return (t.slice(-3).join(' / ') || 'no output').slice(0, 600);
  }
  const msg = [lines[last]];
  for (let i = last + 1; i < lines.length && /^\s+- /.test(lines[i]); i++) msg.push(lines[i]);
  return msg.join('\n');
}
async function pool(list, n, fn) {
  let i = 0;
  await Promise.all(Array.from({ length: Math.min(n, list.length) }, async () => { while (i < list.length) { const it = list[i++]; await fn(it); } }));
}
async function withLock(it, fn) {
  fs.mkdirSync(path.dirname(it.lock), { recursive: true });
  const start = Date.now(); let waited = false;
  for (;;) {
    try { fs.writeFileSync(it.lock, String(process.pid), { flag: 'wx' }); break; } catch {
      let pid = 0; try { pid = Number(fs.readFileSync(it.lock, 'utf8')); } catch { continue; }
      let alive = false; try { if (pid) { process.kill(pid, 0); alive = true; } } catch { alive = false; }
      if (!alive || Date.now() - start > 40 * 60 * 1000) { try { fs.unlinkSync(it.lock); } catch { /* raced */ } continue; }
      waited = true; await new Promise((r) => setTimeout(r, 250));
    }
  }
  try { return await fn(waited); } finally { try { fs.unlinkSync(it.lock); } catch { /* gone */ } }
}
const tempDirs = [];
const KEPT = 'nothing was shipped: the previous raw export and shipped file are unchanged';
const fail = (it, why) => { it.status = 'FAILED'; it.note = why; it.done = true; dropStaged(it); for (const id of byproductsOf(it)) rm(stagedPng(id)); };

/** The lightmaps of a failed asset stay as shipped: say so, after its line. */
function failByproducts(it) {
  for (const id of byproductsOf(it)) {
    rm(stagedPng(id));
    if (!fs.existsSync(M.textures[id]._pub) && !byId.has(id)) continue;
    const b = byproductItem(id, it);
    if (b.done) continue;
    dropStaged(b);
    if (fs.existsSync(b.pub)) { b.status = 'kept'; b.note = `${it.id} FAILED: the shipped lightmap is unchanged`; b.done = true; }
  }
}

/** Run a source script. Everything it writes goes under temporary names (`it.staged`); `finish` ships it. */
async function buildScript(it) {
  await withLock(it, async (waited) => {
    if (waited && !stale(it)) { it.status = 'skipped'; it.note = 'built by another run'; return; }
    const t = performance.now();
    const ext = path.extname(it.raw);
    const tmp = path.join(path.dirname(it.raw), `.${it.id}.${TAG}${ext}`);
    fs.mkdirSync(path.dirname(it.raw), { recursive: true });
    for (const id of byproductsOf(it)) rm(stagedPng(id));
    const r = await run(BLENDER, ['-b', '--factory-startup', '--python-exit-code', '1', '-P', it.src, '--', '--out', tmp, '--seed', '1'], it.log, { KS_STAGE_TAG: TAG });
    it.staged = { raw: tmp };
    it.t = performance.now() - t;
    it.warnings = r.out.split('\n').filter((l) => /^WARNING\b/.test(l));        // the library's bake warnings: counted on the item's line
    if (r.code !== 0 || !fs.existsSync(tmp)) { failByproducts(it); return fail(it, (r.code !== 0 ? reason(r.out) : `the script ended without writing --out (${rel(it.log)})`) + `\n  (${KEPT})`); }
    it.status = 'built';
  });
}
async function buildNode(group) {
  // one run of a .mjs generator serves every texture it is the source of; it writes into a temporary folder
  const it = group[0], t = performance.now();
  const dir = path.join(path.dirname(it.raw), `.node.${TAG}`);
  rm(dir); fs.mkdirSync(dir, { recursive: true });
  const r = await run(process.execPath, [it.src, '--out', dir], it.log);
  for (const g of group) {
    g.staged = { raw: path.join(dir, path.basename(g.raw)) };
    g.t = performance.now() - t;
    if (r.code !== 0) fail(g, reason(r.out));
    else if (!fs.existsSync(g.staged.raw)) fail(g, `${rel(it.src)} did not write ${path.basename(g.raw)} into its --out folder`);
    else g.status = 'built';
  }
  tempDirs.push(dir);
}
async function buildPlaceholders(batch, n) {
  const t = performance.now();
  const args = ['-b', '--factory-startup', '--python-exit-code', '1', '-P', PLACEHOLDER_PY, '--',
    '--assets', batch.filter((b) => b.kind === 'asset').map((b) => b.id).join(','), '--textures', batch.filter((b) => b.kind === 'texture').map((b) => b.id).join(',')];
  const log = path.join(path.dirname(batch[0].log), `_placeholders_${n}.log`);
  const r = await run(BLENDER, args, log);
  for (const it of batch) {
    const line = r.out.split('\n').find((l) => new RegExp(`^(PLACEHOLDER|KEPT|FAILED) ${it.id}\\b`).test(l));
    if (!line) { fail(it, `placeholder generator stopped before ${it.id}: ${reason(r.out)} (${rel(log)})`); continue; }
    if (line.startsWith('FAILED')) {
      const before = r.out.slice(0, r.out.indexOf(line));
      fail(it, reason(before.slice(before.lastIndexOf('Traceback')))); continue;
    }
    it.status = line.startsWith('KEPT') ? 'kept' : 'built'; it.t = (performance.now() - t) / batch.length;
    if (line.startsWith('KEPT')) it.note = `final file, no source script: the placeholder does not replace it. To go back to the placeholder: node tools/build-assets.mjs --reset ${it.id}  (removes ${rel(it.raw)} and ${rel(it.pub)}, then regenerates)`;
  }
}

// ---------------------------------------------------------------- optimise + check + ship
/**
 * Optimise the (staged) raw export into a temporary file beside the target and check THAT file. Returns
 * { ok, tmp, rawSha, stamp, skipped } and ships nothing: `ship` renames, `fail` discards.
 */
async function prepare(it) {
  const src = it.staged?.raw ?? it.raw;
  const s = readStamp(it), rawSha = fileSha(src);
  const ext = path.extname(it.pub);
  const tmp = path.join(path.dirname(it.pub), `.${it.id}.${TAG}${ext}`);
  const out = { ok: false, tmp: null, rawSha, stamp: s, why: '' };
  try {
    const need = FORCE || !!it.staged || !fs.existsSync(it.pub) || s.optimised !== rawSha || it.status === 'built';
    let file = it.pub;
    if (need) {
      fs.mkdirSync(path.dirname(it.pub), { recursive: true });
      const r = await (it.kind === 'asset' ? optimizeAsset(M, it.id, { raw: src, out: tmp }) : optimizeTexture(M, it.id, { raw: src, out: tmp }));
      if (r.skipped) { it.note = it.note || r.skipped; if (it.status === 'built') it.status = 'kept'; }
      else { out.tmp = tmp; file = tmp; }
      s.checked = false;
    }
    if (!NO_CHECK && (FORCE || s.checked !== CHECKER)) {
      const c = await (it.kind === 'asset' ? checkAsset(M, L, it.id, { file }) : checkTexture(M, it.id, { file }));
      if (c.errors.length) { rm(out.tmp); out.tmp = null; out.why = 'check-glb:\n' + c.errors.map((e) => '  - ' + e).join('\n'); return out; }
      s.checked = CHECKER; it.checkInfo = c;
    }
    out.ok = true;
  } catch (e) { rm(tmp); out.tmp = null; out.why = `optimise: ${e.message}`; }
  return out;
}
function ship(it, p) {
  if (it.staged) {
    if (fs.existsSync(it.staged.raw + '.deps.json')) fs.renameSync(it.staged.raw + '.deps.json', it.raw + '.deps.json');
    fs.renameSync(it.staged.raw, it.raw);
    it.staged = null;
  }
  if (p.tmp) fs.renameSync(p.tmp, it.pub);
  p.stamp.optimised = p.rawSha;
  if (it.status === 'built' || (it.status === 'kept' && it.producer === 'placeholder' && PLACEHOLDERS)) { p.stamp.inputs = inputsHash(it); p.stamp.producer = it.producer; }
  writeStamp(it, p.stamp);
  it.done = true;
}
/** The lightmap / light-layer ids the meshes of a (staged) raw GLB point at through their extras. */
function lightmapRefs(file) {
  const out = new Map();
  try {
    for (const n of glbJson(file).nodes ?? []) for (const k of ['lightmap', 'lightLayer']) if (typeof n.extras?.[k] === 'string' && !out.has(n.extras[k])) out.set(n.extras[k], n.name);
  } catch { /* not a GLB: nothing points anywhere */ }
  return out;
}
/** Optimise, check and ship one item together with the lightmaps its script wrote: all of them, or none. */
async function finish(it) {
  if (it.done || it.status === 'FAILED' || it.status === null) return;
  const t = performance.now();
  if (!fs.existsSync(it.staged?.raw ?? it.raw)) { if (it.status !== 'kept') fail(it, `no raw export at ${rel(it.raw)}`); else it.done = true; return; }
  const p = await prepare(it);
  const side = [];
  let why = p.ok ? '' : p.why;
  if (p.ok) {
    const refs = it.status === 'built' && it.staged ? lightmapRefs(it.staged.raw) : new Map();
    for (const id of byproductsOf(it)) {
      const b = byproductItem(id, it);
      if (b.done) continue;
      if (fs.existsSync(stagedPng(id))) { b.staged = { raw: stagedPng(id) }; b.status = 'built'; }
      else if (refs.has(id) && !ALLOW_STALE_LM) {
        // the script ran, its meshes point at this lightmap with the UV1 atlas of THIS run, and it wrote no lightmap:
        // the shipped pair would be a new GLB over a stale (or placeholder) lightmap
        why = `its lightmap ${id} was not written in this run, although mesh '${refs.get(id)}' points at it (extra lightmap / lightLayer) with the UV1 atlas of this run: `
          + `the shipped GLB would sample a stale or placeholder lightmap.\n  Bake it and call bake.save_lightmap(img, '${id}') in ${it.e.source}, `
          + 'or pass --allow-stale-lightmap while iterating on geometry with the bake switched off';
        break;
      }
      else if (it.status === 'built' && fs.existsSync(b.raw) && !pngIsPlaceholder(b.raw)) {
        b.status = 'skipped'; b.note = `${it.e.source} did not write it in this run`;
        if (refs.has(id)) { b.note = `STALE, ${b.note}: --allow-stale-lightmap`; it.stale.push(id); }
        continue;
      }
      else {                                                            // not written yet: the placeholder rule below decides
        if (refs.has(id)) it.stale.push(id);
        continue;
      }
      const bp = await prepare(b);
      side.push([b, bp]);
      if (!bp.ok) { why = `its lightmap ${id} failed ${bp.why}`; break; }
    }
  }
  if (why) {
    rm(p.tmp);
    for (const [b, bp] of side) { rm(bp.tmp); dropStaged(b); b.status = 'kept'; b.note = `${it.id} FAILED: the shipped lightmap is unchanged`; b.done = true; }
    failByproducts(it);
    return fail(it, `${why}\n  (${KEPT})`);
  }
  ship(it, p);
  for (const [b, bp] of side) { ship(b, bp); b.note = `by-product of ${it.e.source}`; }
  it.t += performance.now() - t;
}

async function stage(name) {
  const list = items.filter((it) => it.stage === name && it.status === null);
  const scripts = [], nodes = new Map(), ph = [];
  for (const it of list) {
    if (it.producer === 'byproduct') continue;                        // decided with its zone
    if (it.producer === 'placeholder' && !PLACEHOLDERS) {
      if (fs.existsSync(it.pub)) { it.status = 'kept'; it.note = 'placeholder (no source script yet)'; }
      else fail(it, `no source script (${it.e.source}) and no placeholder in ${rel(it.pub)}: run with --placeholders`);
      continue;
    }
    if (!stale(it)) { it.status = 'skipped'; continue; }
    if (it.producer === 'script') scripts.push(it);
    else if (it.producer === 'node') { if (!nodes.has(it.src)) nodes.set(it.src, []); nodes.get(it.src).push(it); }
    else ph.push(it);
  }
  const jobs = [];
  for (const it of scripts) jobs.push(() => buildScript(it));
  for (const g of nodes.values()) jobs.push(() => buildNode(g));
  const per = Math.max(1, Math.ceil(ph.length / JOBS));
  for (let i = 0, n = 0; i < ph.length; i += per, n++) { const b = ph.slice(i, i + per); jobs.push(() => buildPlaceholders(b, `${name}_${n}`)); }
  await pool(jobs, JOBS, (j) => j());
  // ship what passed before the next stage reads it (zones embed the raw exports of this run's props)
  for (const it of list) if (it.producer !== 'byproduct') await finish(it);
  rm(...tempDirs.splice(0));
}

await stage('tex');
await stage('asset');
await stage('zone');
await stage('late');
// lightmaps that are a zone's by-product and were not shipped with it above: there already, otherwise a placeholder
{
  const by = items.filter((it) => it.producer === 'byproduct' && !it.done && it.status !== 'FAILED');
  const need = [];
  for (const it of by) {
    if (fs.existsSync(it.raw) && !pngIsPlaceholder(it.raw)) { it.status = 'skipped'; it.note = it.note || `by-product of ${it.e.source}`; continue; }
    if (PLACEHOLDERS) { it.producer = 'placeholder'; it.status = null; if (stale(it)) need.push(it); else it.status = 'skipped'; }
    else if (fs.existsSync(it.pub)) { it.status = 'kept'; it.note = `placeholder (${it.e.source} has not written it yet)`; }
    else fail(it, `${it.e.source} did not write ${rel(it.raw)} and there is no placeholder: run with --placeholders`);
  }
  if (need.length) await buildPlaceholders(need, 'lm');
  for (const it of by) await finish(it);
}
for (const it of items) await finish(it);                                // anything left (items whose stage never ran them)

// A rebuilt asset may point at a lightmap that is NOT its own by-product but has a bake script of its own (lm_surface:
// two zone scripts and bake_surface.py over one helper module). If that lightmap's inputs changed and it was not re-baked
// in this run (it was left out of --only), the new GLB's UV1 atlas and the shipped lightmap may not belong together.
const staleLate = [];
for (const it of items.filter((x) => x.kind === 'asset' && x.status === 'built' && x.producer === 'script' && fs.existsSync(x.raw))) {
  for (const [id, mesh] of lightmapRefs(it.raw)) {
    if (!M.textures[id] || byproductsOf(it).includes(id)) continue;
    const x = byId.get(id) ?? makeItem('texture', id);
    if (x.producer !== 'script' || x.stage !== 'late' || x.status === 'built' || x.status === 'FAILED') continue;
    if (fs.existsSync(x.raw) && !pngIsPlaceholder(x.raw) && readStamp(x).inputs === inputsHash(x)) continue;      // baked from what is there now
    if (!staleLate.some((e) => e.id === id)) staleLate.push({ id, by: it.id, mesh, src: x.e.source });
  }
}

// ---------------------------------------------------------------- report
// a by-product is listed right after the asset whose script wrote it
const order = [];
for (const it of items) { if (it.after) continue; order.push(it); for (const b of items) if (b.after === it.id) order.push(b); }
let failed = 0; const counts = {};
for (const it of order) {
  const st = it.status ?? 'skipped';
  counts[st] = (counts[st] ?? 0) + 1;
  if (st === 'FAILED') failed++;
  const size = fs.existsSync(it.pub) ? fmtBytes(fs.statSync(it.pub).size).padStart(10) : ''.padStart(10);
  const ph = it.kind === 'asset' ? glbIsPlaceholder(it.pub, it.id) : null;
  const extra = it.checkInfo && it.kind === 'asset' ? `  tris ${it.checkInfo.tris}/${it.e.triBudget} dc ${it.checkInfo.drawCalls}/${it.e.drawCalls}` : '';
  const nw = it.warnings.length;
  const warn = (nw && st !== 'FAILED' ? `  (${nw} warning${nw === 1 ? '' : 's'}: see ${rel(it.log)})` : '')
    + (it.stale.length ? `  (STALE LIGHTMAP ${it.stale.join(', ')}: not written in this run, shipped under --allow-stale-lightmap)` : '');
  if (st === 'FAILED') console.log(`FAILED   ${it.id}: ${it.note}`);
  else console.log(`${st.padEnd(8)} ${it.id.padEnd(24)} ${size}${st === 'built' ? `  ${(it.t / 1000).toFixed(1)} s` : ''}${extra}${ph ? '  placeholder' : ''}${it.note ? '  (' + it.note + ')' : ''}${warn}`);
}
for (const e of staleLate) {
  console.log(`STALE    ${e.id}: ${e.by} was rebuilt and its mesh '${e.mesh}' points at this lightmap, but ${e.src} was not run again although its inputs changed `
    + `(or it has never been baked): the GLB's UV1 atlas and the shipped lightmap may not belong together.\n  Build them in one run: node tools/build-assets.mjs --only ${e.by},${e.id}`
    + (ALLOW_STALE_LM ? '  (allowed: --allow-stale-lightmap)' : '  (or pass --allow-stale-lightmap while iterating)'));
}
if (staleLate.length) counts.STALE = staleLate.length;
console.log(`${order.length} items: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')} in ${secs(t0)}`);
process.exit(failed || (staleLate.length && !ALLOW_STALE_LM) ? 1 : 0);
